name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: g++
      run: g++ -std=c++14 -Wall ./CPP/Modulo1/VPL2/main.cpp -o main
    - name: run code
      run: ./main 15
